## 310-geth-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bpc-dao-frontend-config
  labels:
    app: bpc-dao-frontend-config
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout 75;

      gzip  on;

      upstream bpc-dao-backend {
        server bpc-dao-backend.main.svc.cluster.local;
      }

      server {
        listen       80;
        server_name  explorer.ndau.io;

        client_max_body_size 64M;

        
        
        location /poll-detail/api/ {
          proxy_pass http://bpc-dao-backend.main.svc.cluster.local/api/;

          proxy_connect_timeout 120;
          proxy_send_timeout 7200;
          proxy_read_timeout 7200;
          send_timeout 7200;
        }
        
        location /poll-detail/ {
          rewrite  ^/poll-detail/(?!api)(.*)$ /$2 last;
        }

        location /all-polls {
          rewrite  ^/all-polls(.*)$ /$1 last;
        }

        location /admin {
          rewrite  ^/admin(.*)$ /$1 last;
        }

        location /proposal-form {
          rewrite  ^/proposal-form(.*)$ /$1 last;
        }

        location /manage-admin {
          rewrite  ^/manage-admin(.*)$ /$1 last;
        }
        
        location /api/ {
          proxy_pass http://bpc-dao-backend.main.svc.cluster.local/api/;

          proxy_connect_timeout 120;
          proxy_send_timeout 7200;
          proxy_read_timeout 7200;
          send_timeout 7200;
        }

        location /socket.io/ {
          proxy_pass http://bpc-dao-backend.main.svc.cluster.local/socket.io/;
        }

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }

        # redirect server error pages to the static page /50x.html
        # error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
